# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow lets you generate SLSA provenance file for your project.
# The generation satisfies level 3 for the provenance requirements - see https://slsa.dev/spec/v0.1/requirements
# The project is an initiative of the OpenSSF (openssf.org) and is developed at
# https://github.com/slsa-framework/slsa-github-generator.
# The provenance file can be verified using https://github.com/slsa-framework/slsa-verifier.
# For more information about SLSA and how it improves the supply-chain, visit slsa.dev.

name: SLSA generic generator
on:
  workflow_dispatch:
  push:
  #release:
  #  types: [created]

env:
  go_version: 1.22.12

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go_version }}

      - name: Set release variables
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            RELEASE_TAG="${{ github.ref_name }}"
          else
            RELEASE_TAG="dev"
          fi
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=go-flare-${RELEASE_TAG}-linux-amd64.zip" >> $GITHUB_ENV

      - run: sudo apt-get update -y && sudo apt-get install -y rsync

      # ========================================================
      #
      # Step 1: Build your artifacts.
      #
      # ========================================================

      - name: Build artifacts
        id: build
        env:
          GOPATH: ${{ github.workspace }}/go
        run: |
          cd avalanchego
          ./scripts/build.sh

      - name: Package build for release
        #if: github.ref_type == 'tag'
        run: |
          cd avalanchego/build
          zip -r ../../${{ env.ARTIFACT_NAME }} .

      - name: Install Cosign
        #if: github.ref_type == 'tag'
        uses: sigstore/cosign-installer@v3.8.1

      - name: Sign release binary
        #if: github.ref_type == 'tag'
        shell: bash
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign sign-blob --yes \
            --output-signature ${{ env.ARTIFACT_NAME }}.sig \
            --output-certificate ${{ env.ARTIFACT_NAME }}.pem \
            ${{ env.ARTIFACT_NAME }}

      - name: Verify release binary signature
        #if: github.ref_type == 'tag'
        shell: bash
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign verify-blob \
            --certificate ${{ env.ARTIFACT_NAME }}.pem \
            --certificate-identity=https://github.com/${{ github.repository }}/.github/workflows/slsa-binary.yml@${{ github.ref }} \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
            --signature ${{ env.ARTIFACT_NAME }}.sig \
            ${{ env.ARTIFACT_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v1
        #if: github.ref_type == 'tag'
        with:
          body: "TODO"
          files: ${{ env.ARTIFACT_NAME }}*

      - name: Archive production artifacts
        #if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: dist-bin
          path: |
            ${{ env.ARTIFACT_NAME }}


      # ========================================================
      #
      # Step 2: Add a step to generate the provenance subjects
      #         as shown below. Update the sha256 sum arguments
      #         to include all binaries that you generate
      #         provenance for.
      #
      # ========================================================
      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail

          # List the artifacts the provenance will refer to.
          files="${{ env.ARTIFACT_NAME }}"
          # Generate the subjects (base64 encoded).
          echo "hashes=$(sha256sum $files | base64 -w0)" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: [build]
    permissions:
      actions: read   # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      upload-assets: true # Optional: Upload to a new release
